### PR TITLE
Split packageName and dtoPackage by dot

### PR DESCRIPTION
**Pull request by cponomaryov**

### CODE REVIEW

**Comment by blast-hardcheese** [comment]
Thank you!

**Comment by cponomaryov** [comment]
Could you please release a new version with this fix?

**Comment by blast-hardcheese** [comment]
Yep, one minute please

**Comment by blast-hardcheese** [comment]
@cponomaryov Released to both maven central and bintray, thank you for your patience

**Comment by cponomaryov** [comment]
@blast-hardcheese I can't see the release in maven central: https://search.maven.org/search?q=a:guardrail-maven-plugin_2.12

**Comment by blast-hardcheese** [comment]
@cponomaryov This was my mistake, I forgot to close and release the repository in Sonatype. I've done it now, it should sync shortly. The released version is 0.37.1.1.

**Comment by cponomaryov** [comment]
@blast-hardcheese thanks!

**Pull request merged**
